{% set name = "napari-ui-tracer" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-ui-tracer-{{ version }}.tar.gz
  sha256: 067ae1d03c6609499272b9014a379f9700df979f448e86015046746e6f443fd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - qtpy >=2.3.0

test:
  imports:
    - napari_ui_tracer
  commands:
    - pip check
  requires:
    - pip
    - napari
    - pyqt
    - numpy <2
    - python {{ python_min }}

about:
  home: https://github.com/dalthviz/napari-ui-tracer
  summary: A plugin to help understand Napari UI components and check their source code definition
  description: A plugin to help understand Napari UI components and locate their code definition
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalthviz
